#!/bin/bash
# Proto file generation script for NanoLink

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROTO_FILE="$SCRIPT_DIR/nanolink.proto"

echo "Generating protobuf code from $PROTO_FILE..."

# Go generation
if command -v protoc &> /dev/null; then
    echo "Generating Go code..."

    # Create output directories
    mkdir -p "$SCRIPT_DIR/../go/nanolink/proto"
    mkdir -p "$SCRIPT_DIR/../../apps/server/internal/proto"

    # Generate Go protobuf + gRPC code for SDK
    protoc \
        --proto_path="$SCRIPT_DIR" \
        --go_out="$SCRIPT_DIR/../go/nanolink/proto" \
        --go_opt=paths=source_relative \
        --go-grpc_out="$SCRIPT_DIR/../go/nanolink/proto" \
        --go-grpc_opt=paths=source_relative \
        "$PROTO_FILE"

    # Copy to apps/server as well
    cp "$SCRIPT_DIR/../go/nanolink/proto/"*.go "$SCRIPT_DIR/../../apps/server/internal/proto/"

    echo "Go code generated successfully!"
else
    echo "protoc not found. Please install protobuf compiler."
    echo "  - macOS: brew install protobuf"
    echo "  - Linux: apt install protobuf-compiler"
    echo "  - Windows: choco install protoc"
    echo ""
    echo "Also install Go plugins:"
    echo "  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest"
    echo "  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest"
fi

# Java generation (if protoc-gen-grpc-java is available)
if [ -f "$SCRIPT_DIR/../java/pom.xml" ]; then
    echo "Java code will be generated by Maven protobuf plugin during build."
fi

echo "Done!"
