import type { ITheme } from "@xterm/xterm"

export interface TerminalTheme {
  id: string
  name: string
  description: string
  theme: ITheme
}

export const terminalThemes: TerminalTheme[] = [
  {
    id: "modern-dark",
    name: "Modern Dark",
    description: "Sleek dark theme with blue accents",
    theme: {
      background: "#09090b",
      foreground: "#fafafa",
      cursor: "#3b82f6",
      cursorAccent: "#09090b",
      selectionBackground: "#3b82f680",
      black: "#09090b",
      red: "#ef4444",
      green: "#22c55e",
      yellow: "#eab308",
      blue: "#3b82f6",
      magenta: "#a855f7",
      cyan: "#06b6d4",
      white: "#fafafa",
      brightBlack: "#52525b",
      brightRed: "#f87171",
      brightGreen: "#4ade80",
      brightYellow: "#facc15",
      brightBlue: "#60a5fa",
      brightMagenta: "#c084fc",
      brightCyan: "#22d3ee",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "classic-green",
    name: "Classic Green",
    description: "Retro monochrome green on black (Matrix style)",
    theme: {
      background: "#0d0d0d",
      foreground: "#00ff00",
      cursor: "#00ff00",
      cursorAccent: "#0d0d0d",
      selectionBackground: "#00ff0040",
      black: "#0d0d0d",
      red: "#00ff00",
      green: "#00ff00",
      yellow: "#00ff00",
      blue: "#00ff00",
      magenta: "#00ff00",
      cyan: "#00ff00",
      white: "#00ff00",
      brightBlack: "#00aa00",
      brightRed: "#00ff00",
      brightGreen: "#00ff00",
      brightYellow: "#00ff00",
      brightBlue: "#00ff00",
      brightMagenta: "#00ff00",
      brightCyan: "#00ff00",
      brightWhite: "#33ff33",
    },
  },
  {
    id: "amber-crt",
    name: "Amber CRT",
    description: "Vintage amber/orange on dark (80s terminal)",
    theme: {
      background: "#1a1200",
      foreground: "#ffb000",
      cursor: "#ffb000",
      cursorAccent: "#1a1200",
      selectionBackground: "#ffb00040",
      black: "#1a1200",
      red: "#ff8c00",
      green: "#ffb000",
      yellow: "#ffd700",
      blue: "#ffb000",
      magenta: "#ff8c00",
      cyan: "#ffc800",
      white: "#ffb000",
      brightBlack: "#996600",
      brightRed: "#ffa500",
      brightGreen: "#ffc800",
      brightYellow: "#ffe066",
      brightBlue: "#ffc800",
      brightMagenta: "#ffa500",
      brightCyan: "#ffd700",
      brightWhite: "#ffe4b5",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    description: "Popular low-contrast theme for reduced eye strain",
    theme: {
      background: "#002b36",
      foreground: "#839496",
      cursor: "#93a1a1",
      cursorAccent: "#002b36",
      selectionBackground: "#073642",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#002b36",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    description: "Purple-tinted dark theme for developers",
    theme: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#bd93f9",
      cursorAccent: "#282a36",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "light",
    name: "Light",
    description: "Clean white background professional theme",
    theme: {
      background: "#ffffff",
      foreground: "#1e1e1e",
      cursor: "#1e1e1e",
      cursorAccent: "#ffffff",
      selectionBackground: "#3b82f620",
      black: "#1e1e1e",
      red: "#dc2626",
      green: "#16a34a",
      yellow: "#ca8a04",
      blue: "#2563eb",
      magenta: "#9333ea",
      cyan: "#0891b2",
      white: "#f5f5f5",
      brightBlack: "#6b7280",
      brightRed: "#ef4444",
      brightGreen: "#22c55e",
      brightYellow: "#eab308",
      brightBlue: "#3b82f6",
      brightMagenta: "#a855f7",
      brightCyan: "#06b6d4",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "hacker",
    name: "Hacker",
    description: "Bright green with cyberpunk aesthetic",
    theme: {
      background: "#000000",
      foreground: "#00ff41",
      cursor: "#00ff41",
      cursorAccent: "#000000",
      selectionBackground: "#00ff4130",
      black: "#000000",
      red: "#ff0033",
      green: "#00ff41",
      yellow: "#ffc107",
      blue: "#00bcd4",
      magenta: "#e91e63",
      cyan: "#00ff41",
      white: "#00ff41",
      brightBlack: "#004b1c",
      brightRed: "#ff4f5a",
      brightGreen: "#00ff41",
      brightYellow: "#ffeb3b",
      brightBlue: "#03a9f4",
      brightMagenta: "#f06292",
      brightCyan: "#4dff7c",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "ubuntu",
    name: "Ubuntu",
    description: "Ubuntu terminal default colors",
    theme: {
      background: "#300a24",
      foreground: "#eeeeec",
      cursor: "#eeeeec",
      cursorAccent: "#300a24",
      selectionBackground: "#b5d5ff50",
      black: "#2e3436",
      red: "#cc0000",
      green: "#4e9a06",
      yellow: "#c4a000",
      blue: "#3465a4",
      magenta: "#75507b",
      cyan: "#06989a",
      white: "#d3d7cf",
      brightBlack: "#555753",
      brightRed: "#ef2929",
      brightGreen: "#8ae234",
      brightYellow: "#fce94f",
      brightBlue: "#729fcf",
      brightMagenta: "#ad7fa8",
      brightCyan: "#34e2e2",
      brightWhite: "#eeeeec",
    },
  },
]

export function getThemeById(id: string): TerminalTheme {
  return terminalThemes.find((t) => t.id === id) || terminalThemes[0]
}

export function getDefaultThemeId(isDark: boolean): string {
  return isDark ? "modern-dark" : "light"
}
