import Foundation

/// Connection state of a remote shell session.
enum ShellStatus: Equatable { case connecting, connected, error, closed }

/// A single rendered line in the terminal console.
enum ShellLineKind { case sys, input, output, error }

struct ShellLine: Identifiable {
    let id = UUID()
    let kind: ShellLineKind
    let text: String
}

/// A remote shell session over `wss://host/ws/shell/:id`. Ports `shell_session.dart`.
///
/// The backend is command-oriented rather than a raw PTY: each `input` message
/// carries a full command line the agent executes (SHELL_EXECUTE), and results
/// come back as one or more `output` messages. `error` messages surface auth /
/// "shell disabled" / dispatch failures. `resize` is advisory.
final class ShellSession: NSObject, ObservableObject {
    let url: URL
    let token: String?
    let ignoreCert: Bool

    @Published private(set) var lines: [ShellLine] = []
    @Published private(set) var status: ShellStatus = .connecting

    private var session: URLSession!
    private var task: URLSessionWebSocketTask?

    init(url: URL, token: String?, ignoreCert: Bool = false) {
        self.url = url
        self.token = token
        self.ignoreCert = ignoreCert
        super.init()
        session = makeSession()
    }

    /// Endpoint display form with the auth token stripped.
    var displayUrl: String {
        var comps = URLComponents(url: url, resolvingAgainstBaseURL: false)
        comps?.queryItems = nil
        return comps?.url?.absoluteString ?? url.absoluteString
    }

    func connect() {
        task?.cancel(with: .goingAway, reason: nil)
        task = nil
        if session == nil {
            session = makeSession()
        }
        setStatus(.connecting)
        var req = URLRequest(url: url)
        if let t = token, !t.isEmpty { req.setValue("Bearer \(t)", forHTTPHeaderField: "Authorization") }
        let t = session.webSocketTask(with: req)
        task = t
        t.resume()
        receiveLoop(t)
    }

    func reconnect() {
        guard status == .error || status == .closed else { return }
        connect()
    }

    /// Send a full command line to the agent.
    func sendInput(_ data: String) {
        guard let task = task, status == .connected else { return }
        guard let payload = try? JSONSerialization.data(withJSONObject: ["type": "input", "data": data]),
              let text = String(data: payload, encoding: .utf8) else { return }
        task.send(.string(text)) { _ in }
    }

    /// Advise the server of the terminal viewport size.
    func resize(cols: Int, rows: Int) {
        guard let task = task, status == .connected else { return }
        guard let payload = try? JSONSerialization.data(withJSONObject: ["type": "resize", "cols": cols, "rows": rows]),
              let text = String(data: payload, encoding: .utf8) else { return }
        task.send(.string(text)) { _ in }
    }

    private func receiveLoop(_ t: URLSessionWebSocketTask) {
        t.receive { [weak self] result in
            guard let self = self else { return }
            switch result {
            case .success(let message):
                switch message {
                case .string(let s): self.onData(s)
                case .data(let d): self.onData(String(data: d, encoding: .utf8) ?? "")
                @unknown default: break
                }
                if self.task === t { self.receiveLoop(t) }
            case .failure(let error):
                guard self.task === t else { return }
                self.task = nil
                self.emit(.error, tr("terminal.connectError", ["err": error.localizedDescription]))
                self.setStatus(.error)
            }
        }
    }

    private func onData(_ raw: String) {
        guard let data = raw.data(using: .utf8),
              let msg = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else { return }
        let type = msg["type"] as? String
        let text = msg["data"] as? String ?? ""
        switch type {
        case "output":
            let success = msg["success"] as? Bool
            if !text.isEmpty { emit(success == false ? .error : .output, text) }
        case "error":
            emit(.error, text)
        default:
            break
        }
    }

    private func emit(_ kind: ShellLineKind, _ text: String) {
        let append = { self.lines.append(ShellLine(kind: kind, text: text)) }
        if Thread.isMainThread { append() }
        else { DispatchQueue.main.async(execute: append) }
    }

    /// Append a locally-generated input echo line.
    func echoInput(_ text: String) { emit(.input, text) }

    /// Append an informational line generated by the local terminal UI.
    func system(_ text: String) { emit(.sys, text) }

    /// Clear the rendered console without closing the remote shell channel.
    func clearLines() {
        let clear = { self.lines.removeAll() }
        if Thread.isMainThread { clear() }
        else { DispatchQueue.main.async(execute: clear) }
    }

    private func setStatus(_ s: ShellStatus) {
        let update = {
            guard self.status != s else { return }
            self.status = s
        }
        if Thread.isMainThread { update() }
        else { DispatchQueue.main.async(execute: update) }
    }

    func close() {
        task?.cancel(with: .goingAway, reason: nil)
        task = nil
        if status != .error {
            emit(.sys, tr("terminal.sessionEnded"))
            setStatus(.closed)
        }
        session.invalidateAndCancel()
        session = nil
    }

    private func makeSession() -> URLSession {
        let configuration = URLSessionConfiguration.default
        configuration.waitsForConnectivity = true
        return URLSession(configuration: configuration, delegate: self, delegateQueue: nil)
    }
}

extension ShellSession: URLSessionWebSocketDelegate {
    func urlSession(_ session: URLSession, webSocketTask: URLSessionWebSocketTask,
                    didOpenWithProtocol negotiatedProtocol: String?) {
        guard task === webSocketTask else { return }
        setStatus(.connected)
    }

    func urlSession(_ session: URLSession, webSocketTask: URLSessionWebSocketTask,
                    didCloseWith closeCode: URLSessionWebSocketTask.CloseCode,
                    reason: Data?) {
        guard task === webSocketTask, status != .error else { return }
        task = nil
        setStatus(.closed)
    }

    func urlSession(_ session: URLSession,
                    didReceive challenge: URLAuthenticationChallenge,
                    completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        guard ignoreCert,
              challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust,
              let trust = challenge.protectionSpace.serverTrust else {
            completionHandler(.performDefaultHandling, nil)
            return
        }
        completionHandler(.useCredential, URLCredential(trust: trust))
    }
}
