// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nanolink.proto

package proto

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandType enumeration
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	CommandType_PROCESS_LIST             CommandType = 1
	CommandType_PROCESS_KILL             CommandType = 2
	CommandType_SERVICE_START            CommandType = 10
	CommandType_SERVICE_STOP             CommandType = 11
	CommandType_SERVICE_RESTART          CommandType = 12
	CommandType_SERVICE_STATUS           CommandType = 13
	CommandType_FILE_TAIL                CommandType = 20
	CommandType_FILE_DOWNLOAD            CommandType = 21
	CommandType_FILE_UPLOAD              CommandType = 22
	CommandType_FILE_TRUNCATE            CommandType = 23
	CommandType_DOCKER_LIST              CommandType = 30
	CommandType_DOCKER_START             CommandType = 31
	CommandType_DOCKER_STOP              CommandType = 32
	CommandType_DOCKER_RESTART           CommandType = 33
	CommandType_DOCKER_LOGS              CommandType = 34
	CommandType_SYSTEM_REBOOT            CommandType = 40
	CommandType_SHELL_EXECUTE            CommandType = 50
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	switch x {
	case CommandType_COMMAND_TYPE_UNSPECIFIED:
		return "COMMAND_TYPE_UNSPECIFIED"
	case CommandType_PROCESS_LIST:
		return "PROCESS_LIST"
	case CommandType_PROCESS_KILL:
		return "PROCESS_KILL"
	case CommandType_SERVICE_START:
		return "SERVICE_START"
	case CommandType_SERVICE_STOP:
		return "SERVICE_STOP"
	case CommandType_SERVICE_RESTART:
		return "SERVICE_RESTART"
	case CommandType_SERVICE_STATUS:
		return "SERVICE_STATUS"
	case CommandType_FILE_TAIL:
		return "FILE_TAIL"
	case CommandType_FILE_DOWNLOAD:
		return "FILE_DOWNLOAD"
	case CommandType_FILE_UPLOAD:
		return "FILE_UPLOAD"
	case CommandType_FILE_TRUNCATE:
		return "FILE_TRUNCATE"
	case CommandType_DOCKER_LIST:
		return "DOCKER_LIST"
	case CommandType_DOCKER_START:
		return "DOCKER_START"
	case CommandType_DOCKER_STOP:
		return "DOCKER_STOP"
	case CommandType_DOCKER_RESTART:
		return "DOCKER_RESTART"
	case CommandType_DOCKER_LOGS:
		return "DOCKER_LOGS"
	case CommandType_SYSTEM_REBOOT:
		return "SYSTEM_REBOOT"
	case CommandType_SHELL_EXECUTE:
		return "SHELL_EXECUTE"
	default:
		return "UNKNOWN"
	}
}

// AgentEvent_EventType enumeration
type AgentEvent_EventType int32

const (
	AgentEvent_CONNECTED    AgentEvent_EventType = 0
	AgentEvent_DISCONNECTED AgentEvent_EventType = 1
	AgentEvent_UPDATED      AgentEvent_EventType = 2
)

func (x AgentEvent_EventType) String() string {
	switch x {
	case AgentEvent_CONNECTED:
		return "CONNECTED"
	case AgentEvent_DISCONNECTED:
		return "DISCONNECTED"
	case AgentEvent_UPDATED:
		return "UPDATED"
	default:
		return "UNKNOWN"
	}
}

// AuthRequest message
type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token        string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname     string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Os           string `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch         string `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AuthRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AuthRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AuthRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

// AuthResponse message
type AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success         bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PermissionLevel int32  `protobuf:"varint,2,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	ErrorMessage    string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetPermissionLevel() int32 {
	if x != nil {
		return x.PermissionLevel
	}
	return 0
}

func (x *AuthResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// CpuMetrics message
type CpuMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsagePercent    float64   `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	CoreCount       uint32    `protobuf:"varint,2,opt,name=core_count,json=coreCount,proto3" json:"core_count,omitempty"`
	PerCoreUsage    []float64 `protobuf:"fixed64,3,rep,packed,name=per_core_usage,json=perCoreUsage,proto3" json:"per_core_usage,omitempty"`
	Model           string    `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Vendor          string    `protobuf:"bytes,5,opt,name=vendor,proto3" json:"vendor,omitempty"`
	FrequencyMhz    uint64    `protobuf:"varint,6,opt,name=frequency_mhz,json=frequencyMhz,proto3" json:"frequency_mhz,omitempty"`
	FrequencyMaxMhz uint64    `protobuf:"varint,7,opt,name=frequency_max_mhz,json=frequencyMaxMhz,proto3" json:"frequency_max_mhz,omitempty"`
	PhysicalCores   uint32    `protobuf:"varint,8,opt,name=physical_cores,json=physicalCores,proto3" json:"physical_cores,omitempty"`
	LogicalCores    uint32    `protobuf:"varint,9,opt,name=logical_cores,json=logicalCores,proto3" json:"logical_cores,omitempty"`
	Architecture    string    `protobuf:"bytes,10,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Temperature     float64   `protobuf:"fixed64,11,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (x *CpuMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CpuMetrics) GetCoreCount() uint32 {
	if x != nil {
		return x.CoreCount
	}
	return 0
}

func (x *CpuMetrics) GetPerCoreUsage() []float64 {
	if x != nil {
		return x.PerCoreUsage
	}
	return nil
}

func (x *CpuMetrics) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CpuMetrics) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *CpuMetrics) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// MemoryMetrics message
type MemoryMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total          uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used           uint64 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Available      uint64 `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	SwapTotal      uint64 `protobuf:"varint,4,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed       uint64 `protobuf:"varint,5,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	Cached         uint64 `protobuf:"varint,6,opt,name=cached,proto3" json:"cached,omitempty"`
	Buffers        uint64 `protobuf:"varint,7,opt,name=buffers,proto3" json:"buffers,omitempty"`
	MemoryType     string `protobuf:"bytes,8,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`
	MemorySpeedMhz uint32 `protobuf:"varint,9,opt,name=memory_speed_mhz,json=memorySpeedMhz,proto3" json:"memory_speed_mhz,omitempty"`
}

func (x *MemoryMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryMetrics) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MemoryMetrics) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

// DiskMetrics message
type DiskMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MountPoint    string  `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Device        string  `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	FsType        string  `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	Total         uint64  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64  `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	Available     uint64  `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	ReadBytesSec  uint64  `protobuf:"varint,7,opt,name=read_bytes_sec,json=readBytesSec,proto3" json:"read_bytes_sec,omitempty"`
	WriteBytesSec uint64  `protobuf:"varint,8,opt,name=write_bytes_sec,json=writeBytesSec,proto3" json:"write_bytes_sec,omitempty"`
	Model         string  `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	Serial        string  `protobuf:"bytes,10,opt,name=serial,proto3" json:"serial,omitempty"`
	DiskType      string  `protobuf:"bytes,11,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	ReadIops      uint64  `protobuf:"varint,12,opt,name=read_iops,json=readIops,proto3" json:"read_iops,omitempty"`
	WriteIops     uint64  `protobuf:"varint,13,opt,name=write_iops,json=writeIops,proto3" json:"write_iops,omitempty"`
	Temperature   float64 `protobuf:"fixed64,14,opt,name=temperature,proto3" json:"temperature,omitempty"`
	HealthStatus  string  `protobuf:"bytes,15,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
}

func (x *DiskMetrics) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetrics) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

// NetworkMetrics message
type NetworkMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interface     string   `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	RxBytesSec    uint64   `protobuf:"varint,2,opt,name=rx_bytes_sec,json=rxBytesSec,proto3" json:"rx_bytes_sec,omitempty"`
	TxBytesSec    uint64   `protobuf:"varint,3,opt,name=tx_bytes_sec,json=txBytesSec,proto3" json:"tx_bytes_sec,omitempty"`
	RxPacketsSec  uint64   `protobuf:"varint,4,opt,name=rx_packets_sec,json=rxPacketsSec,proto3" json:"rx_packets_sec,omitempty"`
	TxPacketsSec  uint64   `protobuf:"varint,5,opt,name=tx_packets_sec,json=txPacketsSec,proto3" json:"tx_packets_sec,omitempty"`
	IsUp          bool     `protobuf:"varint,6,opt,name=is_up,json=isUp,proto3" json:"is_up,omitempty"`
	MacAddress    string   `protobuf:"bytes,7,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddresses   []string `protobuf:"bytes,8,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	SpeedMbps     uint64   `protobuf:"varint,9,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`
	InterfaceType string   `protobuf:"bytes,10,opt,name=interface_type,json=interfaceType,proto3" json:"interface_type,omitempty"`
}

func (x *NetworkMetrics) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *NetworkMetrics) GetRxBytesSec() uint64 {
	if x != nil {
		return x.RxBytesSec
	}
	return 0
}

func (x *NetworkMetrics) GetTxBytesSec() uint64 {
	if x != nil {
		return x.TxBytesSec
	}
	return 0
}

// GpuMetrics message
type GpuMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index            uint32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name             string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vendor           string  `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	UsagePercent     float64 `protobuf:"fixed64,4,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	MemoryTotal      uint64  `protobuf:"varint,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed       uint64  `protobuf:"varint,6,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	Temperature      float64 `protobuf:"fixed64,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	FanSpeedPercent  uint32  `protobuf:"varint,8,opt,name=fan_speed_percent,json=fanSpeedPercent,proto3" json:"fan_speed_percent,omitempty"`
	PowerWatts       uint32  `protobuf:"varint,9,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	PowerLimitWatts  uint32  `protobuf:"varint,10,opt,name=power_limit_watts,json=powerLimitWatts,proto3" json:"power_limit_watts,omitempty"`
	ClockCoreMhz     uint64  `protobuf:"varint,11,opt,name=clock_core_mhz,json=clockCoreMhz,proto3" json:"clock_core_mhz,omitempty"`
	ClockMemoryMhz   uint64  `protobuf:"varint,12,opt,name=clock_memory_mhz,json=clockMemoryMhz,proto3" json:"clock_memory_mhz,omitempty"`
	DriverVersion    string  `protobuf:"bytes,13,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	PcieGeneration   string  `protobuf:"bytes,14,opt,name=pcie_generation,json=pcieGeneration,proto3" json:"pcie_generation,omitempty"`
	EncoderUsage     float64 `protobuf:"fixed64,15,opt,name=encoder_usage,json=encoderUsage,proto3" json:"encoder_usage,omitempty"`
	DecoderUsage     float64 `protobuf:"fixed64,16,opt,name=decoder_usage,json=decoderUsage,proto3" json:"decoder_usage,omitempty"`
}

func (x *GpuMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GpuMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *GpuMetrics) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *GpuMetrics) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *GpuMetrics) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// SystemInfo message
type SystemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OsName           string `protobuf:"bytes,1,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsVersion        string `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	KernelVersion    string `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Hostname         string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	BootTime         uint64 `protobuf:"varint,5,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	UptimeSeconds    uint64 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	MotherboardModel string `protobuf:"bytes,7,opt,name=motherboard_model,json=motherboardModel,proto3" json:"motherboard_model,omitempty"`
	MotherboardVendor string `protobuf:"bytes,8,opt,name=motherboard_vendor,json=motherboardVendor,proto3" json:"motherboard_vendor,omitempty"`
	BiosVersion      string `protobuf:"bytes,9,opt,name=bios_version,json=biosVersion,proto3" json:"bios_version,omitempty"`
	SystemModel      string `protobuf:"bytes,10,opt,name=system_model,json=systemModel,proto3" json:"system_model,omitempty"`
	SystemVendor     string `protobuf:"bytes,11,opt,name=system_vendor,json=systemVendor,proto3" json:"system_vendor,omitempty"`
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// Metrics message
type Metrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp   uint64            `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cpu         *CpuMetrics       `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory      *MemoryMetrics    `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks       []*DiskMetrics    `protobuf:"bytes,4,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks    []*NetworkMetrics `protobuf:"bytes,5,rep,name=networks,proto3" json:"networks,omitempty"`
	LoadAverage []float64         `protobuf:"fixed64,6,rep,packed,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	Hostname    string            `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Gpus        []*GpuMetrics     `protobuf:"bytes,8,rep,name=gpus,proto3" json:"gpus,omitempty"`
	SystemInfo  *SystemInfo       `protobuf:"bytes,9,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
}

func (x *Metrics) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metrics) GetCpu() *CpuMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Metrics) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Metrics) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Metrics) GetNetworks() []*NetworkMetrics {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *Metrics) GetLoadAverage() []float64 {
	if x != nil {
		return x.LoadAverage
	}
	return nil
}

func (x *Metrics) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Metrics) GetGpus() []*GpuMetrics {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *Metrics) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

// Command message
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId  string            `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type       CommandType       `protobuf:"varint,2,opt,name=type,proto3,enum=nanolink.CommandType" json:"type,omitempty"`
	Target     string            `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Params     map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SuperToken string            `protobuf:"bytes,5,opt,name=super_token,json=superToken,proto3" json:"super_token,omitempty"`
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Command) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Command) GetSuperToken() string {
	if x != nil {
		return x.SuperToken
	}
	return ""
}

// CommandResult message
type CommandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId   string           `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success     bool             `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output      string           `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error       string           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	FileContent []byte           `protobuf:"bytes,5,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	Processes   []*ProcessInfo   `protobuf:"bytes,6,rep,name=processes,proto3" json:"processes,omitempty"`
	Containers  []*ContainerInfo `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty"`
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *CommandResult) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *CommandResult) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

// ProcessInfo message
type ProcessInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid         uint32  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User        string  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	CpuPercent  float64 `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes uint64  `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Status      string  `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	StartTime   uint64  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
}

func (x *ProcessInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ContainerInfo message
type ContainerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image   string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	State   string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Created uint64 `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Heartbeat message
type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp     uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UptimeSeconds uint64 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
}

func (x *Heartbeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// HeartbeatAck message
type HeartbeatAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HeartbeatAck) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MetricsStreamRequest message
type MetricsStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*MetricsStreamRequest_Metrics
	//	*MetricsStreamRequest_Heartbeat
	//	*MetricsStreamRequest_CommandResult
	Request isMetricsStreamRequest_Request `protobuf_oneof:"request"`
}

type isMetricsStreamRequest_Request interface {
	isMetricsStreamRequest_Request()
}

type MetricsStreamRequest_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,1,opt,name=metrics,proto3,oneof"`
}

type MetricsStreamRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type MetricsStreamRequest_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,3,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*MetricsStreamRequest_Metrics) isMetricsStreamRequest_Request() {}
func (*MetricsStreamRequest_Heartbeat) isMetricsStreamRequest_Request() {}
func (*MetricsStreamRequest_CommandResult) isMetricsStreamRequest_Request() {}

func (x *MetricsStreamRequest) GetRequest() isMetricsStreamRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *MetricsStreamRequest) GetMetrics() *Metrics {
	if x, ok := x.GetRequest().(*MetricsStreamRequest_Metrics); ok {
		return x.Metrics
	}
	return nil
}

func (x *MetricsStreamRequest) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetRequest().(*MetricsStreamRequest_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *MetricsStreamRequest) GetCommandResult() *CommandResult {
	if x, ok := x.GetRequest().(*MetricsStreamRequest_CommandResult); ok {
		return x.CommandResult
	}
	return nil
}

// MetricsStreamResponse message
type MetricsStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*MetricsStreamResponse_Command
	//	*MetricsStreamResponse_HeartbeatAck
	//	*MetricsStreamResponse_ConfigUpdate
	Response isMetricsStreamResponse_Response `protobuf_oneof:"response"`
}

type isMetricsStreamResponse_Response interface {
	isMetricsStreamResponse_Response()
}

type MetricsStreamResponse_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type MetricsStreamResponse_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type MetricsStreamResponse_ConfigUpdate struct {
	ConfigUpdate *ServerConfig `protobuf:"bytes,3,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

func (*MetricsStreamResponse_Command) isMetricsStreamResponse_Response() {}
func (*MetricsStreamResponse_HeartbeatAck) isMetricsStreamResponse_Response() {}
func (*MetricsStreamResponse_ConfigUpdate) isMetricsStreamResponse_Response() {}

func (x *MetricsStreamResponse) GetResponse() isMetricsStreamResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MetricsStreamResponse) GetCommand() *Command {
	if x, ok := x.GetResponse().(*MetricsStreamResponse_Command); ok {
		return x.Command
	}
	return nil
}

func (x *MetricsStreamResponse) GetHeartbeatAck() *HeartbeatAck {
	if x, ok := x.GetResponse().(*MetricsStreamResponse_HeartbeatAck); ok {
		return x.HeartbeatAck
	}
	return nil
}

func (x *MetricsStreamResponse) GetConfigUpdate() *ServerConfig {
	if x, ok := x.GetResponse().(*MetricsStreamResponse_ConfigUpdate); ok {
		return x.ConfigUpdate
	}
	return nil
}

// MetricsAck message
type MetricsAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *MetricsAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsAck) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatRequest message
type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UptimeSeconds uint64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatResponse message
type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTimestamp uint64 `protobuf:"varint,1,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	ConfigChanged   bool   `protobuf:"varint,2,opt,name=config_changed,json=configChanged,proto3" json:"config_changed,omitempty"`
}

func (x *HeartbeatResponse) GetServerTimestamp() uint64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *HeartbeatResponse) GetConfigChanged() bool {
	if x != nil {
		return x.ConfigChanged
	}
	return false
}

// MetricsSyncRequest message
type MetricsSyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId           string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	LastSyncTimestamp uint64 `protobuf:"varint,2,opt,name=last_sync_timestamp,json=lastSyncTimestamp,proto3" json:"last_sync_timestamp,omitempty"`
}

func (x *MetricsSyncRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsSyncRequest) GetLastSyncTimestamp() uint64 {
	if x != nil {
		return x.LastSyncTimestamp
	}
	return 0
}

// MetricsSyncResponse message
type MetricsSyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success         bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Metrics         []*Metrics `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	ServerTimestamp uint64     `protobuf:"varint,3,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
}

func (x *MetricsSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsSyncResponse) GetMetrics() []*Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// AgentInfoRequest message
type AgentInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
}

func (x *AgentInfoRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// AgentInfoResponse message
type AgentInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId          string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname         string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os               string   `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch             string   `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Version          string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	PermissionLevel  int32    `protobuf:"varint,6,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	ConnectedAt      uint64   `protobuf:"varint,7,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastMetricsAt    uint64   `protobuf:"varint,8,opt,name=last_metrics_at,json=lastMetricsAt,proto3" json:"last_metrics_at,omitempty"`
	ConnectedServers []string `protobuf:"bytes,9,rep,name=connected_servers,json=connectedServers,proto3" json:"connected_servers,omitempty"`
}

func (x *AgentInfoResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfoResponse) GetPermissionLevel() int32 {
	if x != nil {
		return x.PermissionLevel
	}
	return 0
}

func (x *AgentInfoResponse) GetConnectedAt() uint64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

// ServerConfig message
type ServerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetricsIntervalMs     uint64   `protobuf:"varint,1,opt,name=metrics_interval_ms,json=metricsIntervalMs,proto3" json:"metrics_interval_ms,omitempty"`
	HeartbeatIntervalMs   uint64   `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	EnableDetailedMetrics bool     `protobuf:"varint,3,opt,name=enable_detailed_metrics,json=enableDetailedMetrics,proto3" json:"enable_detailed_metrics,omitempty"`
	EnabledCollectors     []string `protobuf:"bytes,4,rep,name=enabled_collectors,json=enabledCollectors,proto3" json:"enabled_collectors,omitempty"`
}

func (x *ServerConfig) GetMetricsIntervalMs() uint64 {
	if x != nil {
		return x.MetricsIntervalMs
	}
	return 0
}

func (x *ServerConfig) GetHeartbeatIntervalMs() uint64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

// Dashboard service messages

// WatchAgentsRequest message
type WatchAgentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncludeInitial bool `protobuf:"varint,1,opt,name=include_initial,json=includeInitial,proto3" json:"include_initial,omitempty"`
}

func (x *WatchAgentsRequest) GetIncludeInitial() bool {
	if x != nil {
		return x.IncludeInitial
	}
	return false
}

// AgentEvent message
type AgentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType AgentEvent_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=nanolink.AgentEvent_EventType" json:"event_type,omitempty"`
	Agent     *AgentInfoResponse   `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Timestamp uint64               `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *AgentEvent) GetEventType() AgentEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return AgentEvent_CONNECTED
}

func (x *AgentEvent) GetAgent() *AgentInfoResponse {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *AgentEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// WatchMetricsRequest message
type WatchMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentIds   []string `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	IntervalMs uint64   `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
}

func (x *WatchMetricsRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *WatchMetricsRequest) GetIntervalMs() uint64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// GetAgentsRequest message
type GetAgentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncludeOffline bool `protobuf:"varint,1,opt,name=include_offline,json=includeOffline,proto3" json:"include_offline,omitempty"`
}

func (x *GetAgentsRequest) GetIncludeOffline() bool {
	if x != nil {
		return x.IncludeOffline
	}
	return false
}

// GetAgentsResponse message
type GetAgentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*AgentInfoResponse `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
}

func (x *GetAgentsResponse) GetAgents() []*AgentInfoResponse {
	if x != nil {
		return x.Agents
	}
	return nil
}

// GetAgentMetricsRequest message
type GetAgentMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
}

func (x *GetAgentMetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// DashboardCommandRequest message
type DashboardCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId       string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command       *Command `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	DashboardUser string   `protobuf:"bytes,3,opt,name=dashboard_user,json=dashboardUser,proto3" json:"dashboard_user,omitempty"`
}

func (x *DashboardCommandRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DashboardCommandRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DashboardCommandRequest) GetDashboardUser() string {
	if x != nil {
		return x.DashboardUser
	}
	return ""
}

func init() {
}
