// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: nanolink.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// NanoLinkServiceClient is the client API for NanoLinkService service.
type NanoLinkServiceClient interface {
	// Authenticate authenticates the agent and returns permission level
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// StreamMetrics is a bidirectional stream for metrics upload and command dispatch
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (NanoLinkService_StreamMetricsClient, error)
	// ReportMetrics is a simple unary RPC for one-time metrics report
	ReportMetrics(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*MetricsAck, error)
	// ExecuteCommand sends a command to the agent and waits for result
	ExecuteCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResult, error)
	// Heartbeat keeps the connection alive
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// SyncMetrics syncs buffered metrics after reconnection
	SyncMetrics(ctx context.Context, in *MetricsSyncRequest, opts ...grpc.CallOption) (*MetricsSyncResponse, error)
	// GetAgentInfo returns current agent information
	GetAgentInfo(ctx context.Context, in *AgentInfoRequest, opts ...grpc.CallOption) (*AgentInfoResponse, error)
}

type nanoLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNanoLinkServiceClient(cc grpc.ClientConnInterface) NanoLinkServiceClient {
	return &nanoLinkServiceClient{cc}
}

func (c *nanoLinkServiceClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/nanolink.NanoLinkService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoLinkServiceClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (NanoLinkService_StreamMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NanoLinkService_ServiceDesc.Streams[0], "/nanolink.NanoLinkService/StreamMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &nanoLinkServiceStreamMetricsClient{stream}
	return x, nil
}

type NanoLinkService_StreamMetricsClient interface {
	Send(*MetricsStreamRequest) error
	Recv() (*MetricsStreamResponse, error)
	grpc.ClientStream
}

type nanoLinkServiceStreamMetricsClient struct {
	grpc.ClientStream
}

func (x *nanoLinkServiceStreamMetricsClient) Send(m *MetricsStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nanoLinkServiceStreamMetricsClient) Recv() (*MetricsStreamResponse, error) {
	m := new(MetricsStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nanoLinkServiceClient) ReportMetrics(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*MetricsAck, error) {
	out := new(MetricsAck)
	err := c.cc.Invoke(ctx, "/nanolink.NanoLinkService/ReportMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoLinkServiceClient) ExecuteCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResult, error) {
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, "/nanolink.NanoLinkService/ExecuteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoLinkServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/nanolink.NanoLinkService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoLinkServiceClient) SyncMetrics(ctx context.Context, in *MetricsSyncRequest, opts ...grpc.CallOption) (*MetricsSyncResponse, error) {
	out := new(MetricsSyncResponse)
	err := c.cc.Invoke(ctx, "/nanolink.NanoLinkService/SyncMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoLinkServiceClient) GetAgentInfo(ctx context.Context, in *AgentInfoRequest, opts ...grpc.CallOption) (*AgentInfoResponse, error) {
	out := new(AgentInfoResponse)
	err := c.cc.Invoke(ctx, "/nanolink.NanoLinkService/GetAgentInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NanoLinkServiceServer is the server API for NanoLinkService service.
type NanoLinkServiceServer interface {
	// Authenticate authenticates the agent and returns permission level
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	// StreamMetrics is a bidirectional stream for metrics upload and command dispatch
	StreamMetrics(NanoLinkService_StreamMetricsServer) error
	// ReportMetrics is a simple unary RPC for one-time metrics report
	ReportMetrics(context.Context, *Metrics) (*MetricsAck, error)
	// ExecuteCommand sends a command to the agent and waits for result
	ExecuteCommand(context.Context, *Command) (*CommandResult, error)
	// Heartbeat keeps the connection alive
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// SyncMetrics syncs buffered metrics after reconnection
	SyncMetrics(context.Context, *MetricsSyncRequest) (*MetricsSyncResponse, error)
	// GetAgentInfo returns current agent information
	GetAgentInfo(context.Context, *AgentInfoRequest) (*AgentInfoResponse, error)
	mustEmbedUnimplementedNanoLinkServiceServer()
}

// UnimplementedNanoLinkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNanoLinkServiceServer struct {
}

func (UnimplementedNanoLinkServiceServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedNanoLinkServiceServer) StreamMetrics(NanoLinkService_StreamMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedNanoLinkServiceServer) ReportMetrics(context.Context, *Metrics) (*MetricsAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedNanoLinkServiceServer) ExecuteCommand(context.Context, *Command) (*CommandResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedNanoLinkServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNanoLinkServiceServer) SyncMetrics(context.Context, *MetricsSyncRequest) (*MetricsSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMetrics not implemented")
}
func (UnimplementedNanoLinkServiceServer) GetAgentInfo(context.Context, *AgentInfoRequest) (*AgentInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentInfo not implemented")
}
func (UnimplementedNanoLinkServiceServer) mustEmbedUnimplementedNanoLinkServiceServer() {}

// UnsafeNanoLinkServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeNanoLinkServiceServer interface {
	mustEmbedUnimplementedNanoLinkServiceServer()
}

func RegisterNanoLinkServiceServer(s grpc.ServiceRegistrar, srv NanoLinkServiceServer) {
	s.RegisterService(&NanoLinkService_ServiceDesc, srv)
}

func _NanoLinkService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoLinkServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanolink.NanoLinkService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoLinkServiceServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NanoLinkService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NanoLinkServiceServer).StreamMetrics(&nanoLinkServiceStreamMetricsServer{stream})
}

type NanoLinkService_StreamMetricsServer interface {
	Send(*MetricsStreamResponse) error
	Recv() (*MetricsStreamRequest, error)
	grpc.ServerStream
}

type nanoLinkServiceStreamMetricsServer struct {
	grpc.ServerStream
}

func (x *nanoLinkServiceStreamMetricsServer) Send(m *MetricsStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nanoLinkServiceStreamMetricsServer) Recv() (*MetricsStreamRequest, error) {
	m := new(MetricsStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NanoLinkService_ReportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metrics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoLinkServiceServer).ReportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanolink.NanoLinkService/ReportMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoLinkServiceServer).ReportMetrics(ctx, req.(*Metrics))
	}
	return interceptor(ctx, in, info, handler)
}

func _NanoLinkService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoLinkServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanolink.NanoLinkService/ExecuteCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoLinkServiceServer).ExecuteCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _NanoLinkService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoLinkServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanolink.NanoLinkService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoLinkServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NanoLinkService_SyncMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoLinkServiceServer).SyncMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanolink.NanoLinkService/SyncMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoLinkServiceServer).SyncMetrics(ctx, req.(*MetricsSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NanoLinkService_GetAgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoLinkServiceServer).GetAgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanolink.NanoLinkService/GetAgentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoLinkServiceServer).GetAgentInfo(ctx, req.(*AgentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NanoLinkService_ServiceDesc is the grpc.ServiceDesc for NanoLinkService service.
var NanoLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanolink.NanoLinkService",
	HandlerType: (*NanoLinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _NanoLinkService_Authenticate_Handler,
		},
		{
			MethodName: "ReportMetrics",
			Handler:    _NanoLinkService_ReportMetrics_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _NanoLinkService_ExecuteCommand_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NanoLinkService_Heartbeat_Handler,
		},
		{
			MethodName: "SyncMetrics",
			Handler:    _NanoLinkService_SyncMetrics_Handler,
		},
		{
			MethodName: "GetAgentInfo",
			Handler:    _NanoLinkService_GetAgentInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _NanoLinkService_StreamMetrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nanolink.proto",
}

// DashboardServiceClient is the client API for DashboardService service.
type DashboardServiceClient interface {
	// WatchAgents streams agent connection/disconnection events
	WatchAgents(ctx context.Context, in *WatchAgentsRequest, opts ...grpc.CallOption) (DashboardService_WatchAgentsClient, error)
	// WatchMetrics streams real-time metrics for specified agents
	WatchMetrics(ctx context.Context, in *WatchMetricsRequest, opts ...grpc.CallOption) (DashboardService_WatchMetricsClient, error)
	// GetAgents returns list of connected agents
	GetAgents(ctx context.Context, in *GetAgentsRequest, opts ...grpc.CallOption) (*GetAgentsResponse, error)
	// GetAgentMetrics returns current metrics for an agent
	GetAgentMetrics(ctx context.Context, in *GetAgentMetricsRequest, opts ...grpc.CallOption) (*Metrics, error)
	// SendCommand sends command to agent through dashboard
	SendCommand(ctx context.Context, in *DashboardCommandRequest, opts ...grpc.CallOption) (*CommandResult, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) WatchAgents(ctx context.Context, in *WatchAgentsRequest, opts ...grpc.CallOption) (DashboardService_WatchAgentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DashboardService_ServiceDesc.Streams[0], "/nanolink.DashboardService/WatchAgents", opts...)
	if err != nil {
		return nil, err
	}
	x := &dashboardServiceWatchAgentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DashboardService_WatchAgentsClient interface {
	Recv() (*AgentEvent, error)
	grpc.ClientStream
}

type dashboardServiceWatchAgentsClient struct {
	grpc.ClientStream
}

func (x *dashboardServiceWatchAgentsClient) Recv() (*AgentEvent, error) {
	m := new(AgentEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dashboardServiceClient) WatchMetrics(ctx context.Context, in *WatchMetricsRequest, opts ...grpc.CallOption) (DashboardService_WatchMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DashboardService_ServiceDesc.Streams[1], "/nanolink.DashboardService/WatchMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &dashboardServiceWatchMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DashboardService_WatchMetricsClient interface {
	Recv() (*Metrics, error)
	grpc.ClientStream
}

type dashboardServiceWatchMetricsClient struct {
	grpc.ClientStream
}

func (x *dashboardServiceWatchMetricsClient) Recv() (*Metrics, error) {
	m := new(Metrics)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dashboardServiceClient) GetAgents(ctx context.Context, in *GetAgentsRequest, opts ...grpc.CallOption) (*GetAgentsResponse, error) {
	out := new(GetAgentsResponse)
	err := c.cc.Invoke(ctx, "/nanolink.DashboardService/GetAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetAgentMetrics(ctx context.Context, in *GetAgentMetricsRequest, opts ...grpc.CallOption) (*Metrics, error) {
	out := new(Metrics)
	err := c.cc.Invoke(ctx, "/nanolink.DashboardService/GetAgentMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) SendCommand(ctx context.Context, in *DashboardCommandRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, "/nanolink.DashboardService/SendCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
type DashboardServiceServer interface {
	// WatchAgents streams agent connection/disconnection events
	WatchAgents(*WatchAgentsRequest, DashboardService_WatchAgentsServer) error
	// WatchMetrics streams real-time metrics for specified agents
	WatchMetrics(*WatchMetricsRequest, DashboardService_WatchMetricsServer) error
	// GetAgents returns list of connected agents
	GetAgents(context.Context, *GetAgentsRequest) (*GetAgentsResponse, error)
	// GetAgentMetrics returns current metrics for an agent
	GetAgentMetrics(context.Context, *GetAgentMetricsRequest) (*Metrics, error)
	// SendCommand sends command to agent through dashboard
	SendCommand(context.Context, *DashboardCommandRequest) (*CommandResult, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDashboardServiceServer struct {
}

func (UnimplementedDashboardServiceServer) WatchAgents(*WatchAgentsRequest, DashboardService_WatchAgentsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchAgents not implemented")
}
func (UnimplementedDashboardServiceServer) WatchMetrics(*WatchMetricsRequest, DashboardService_WatchMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchMetrics not implemented")
}
func (UnimplementedDashboardServiceServer) GetAgents(context.Context, *GetAgentsRequest) (*GetAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgents not implemented")
}
func (UnimplementedDashboardServiceServer) GetAgentMetrics(context.Context, *GetAgentMetricsRequest) (*Metrics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentMetrics not implemented")
}
func (UnimplementedDashboardServiceServer) SendCommand(context.Context, *DashboardCommandRequest) (*CommandResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_WatchAgents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchAgentsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DashboardServiceServer).WatchAgents(m, &dashboardServiceWatchAgentsServer{stream})
}

type DashboardService_WatchAgentsServer interface {
	Send(*AgentEvent) error
	grpc.ServerStream
}

type dashboardServiceWatchAgentsServer struct {
	grpc.ServerStream
}

func (x *dashboardServiceWatchAgentsServer) Send(m *AgentEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _DashboardService_WatchMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DashboardServiceServer).WatchMetrics(m, &dashboardServiceWatchMetricsServer{stream})
}

type DashboardService_WatchMetricsServer interface {
	Send(*Metrics) error
	grpc.ServerStream
}

type dashboardServiceWatchMetricsServer struct {
	grpc.ServerStream
}

func (x *dashboardServiceWatchMetricsServer) Send(m *Metrics) error {
	return x.ServerStream.SendMsg(m)
}

func _DashboardService_GetAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanolink.DashboardService/GetAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetAgents(ctx, req.(*GetAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetAgentMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetAgentMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanolink.DashboardService/GetAgentMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetAgentMetrics(ctx, req.(*GetAgentMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanolink.DashboardService/SendCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).SendCommand(ctx, req.(*DashboardCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanolink.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgents",
			Handler:    _DashboardService_GetAgents_Handler,
		},
		{
			MethodName: "GetAgentMetrics",
			Handler:    _DashboardService_GetAgentMetrics_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _DashboardService_SendCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchAgents",
			Handler:       _DashboardService_WatchAgents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchMetrics",
			Handler:       _DashboardService_WatchMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nanolink.proto",
}
